export * from './home.page'
export * from './login.page'
export * from './dashboard.page'
export * from './post.page'
export * from './contact.page'
export * from './about.page'
export * from './projects.page'