export const HOME = '/'
export const ABOUT = '/about'
export const BLOG = '/blog'
export const CONTACT = '/contact'
export const PROJECTS = '/projects'
export const THANK_YOU = '/thank-you'
export const SINGLE_POST = '/:slug'